import express from 'express'
import cors from 'cors'
import path from 'path'
import { fileURLToPath } from 'url'
import { config, assertLlmConfigured } from './config.js'
import { initAdmin, isQuotaEnabled } from './auth/firebaseAdmin.js'
import { requireAuth } from './auth/requireAuth.js'
import { getQuota, reserveTailor, refundTailor } from './quota.js'
import { runTailorAgent } from './agent/tailorAgent.js'

initAdmin()

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const app = express()
app.use(express.json({ limit: '1mb' }))

// In production, when frontend and backend share the same origin, 
// allow same-origin requests while preserving your existing CORS checks.
app.use(
  cors({
    origin(origin, cb) {
      if (!origin || config.allowedOrigins.includes(origin)) return cb(null, true)
      cb(new Error(`Origin ${origin} not allowed`))
    },
  })
)

// =======================
// API Routes
// =======================

app.get('/api/health', (_req, res) => {
  res.json({
    ok: true,
    llmConfigured: Boolean(config.llm.apiKey),
    quotaEnforced: isQuotaEnabled(),
    authRequired: !config.firebase.authDisabled,
    models: config.llm.models,
  })
})

app.get('/api/quota', requireAuth, async (req, res) => {
  try {
    res.json(await getQuota(req.user.uid))
  } catch (err) {
    res.status(500).json({ error: err.message })
  }
})

// The tailoring agent SSE endpoint
app.post('/api/tailor', requireAuth, async (req, res) => {
  const { baseResume, jobDescription } = req.body || {}

  let reserved = false
  try {
    assertLlmConfigured()
    if (!baseResume || !jobDescription) {
      throw Object.assign(new Error('A base résumé and job description are required.'), { status: 400, code: 'BAD_REQUEST' })
    }
    reserved = (await reserveTailor(req.user.uid)).enforced
  } catch (err) {
    return res.status(err.status || 500).json({ error: err.message || 'Tailoring failed.', code: err.code })
  }

  // Begin the event stream.
  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache, no-transform')
  res.setHeader('Connection', 'keep-alive')
  res.flushHeaders?.()
  const send = (event, data) => res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)

  try {
    const result = await runTailorAgent({ baseResume, jobDescription, onProgress: (p) => send('progress', p) })
    const quota = await getQuota(req.user.uid)
    send('result', { ...result, quota })
    res.end()
  } catch (err) {
    if (reserved) await refundTailor(req.user.uid)
    if (!err.code) console.error('[tailor] error:', err)
    send('error', { error: err.message || 'Tailoring failed.', code: err.code })
    res.end()
  }
})

// =======================
// Static Build & SPA Fallback
// =======================

// Resolves to the 'dist' directory located in the project root
const distPath = path.resolve(__dirname, '../dist')

// Serve static assets generated by Vite
app.use(express.static(distPath))

// Single Page Application (SPA) catch-all: send index.html for any non-API route
app.get('*', (req, res) => {
  res.sendFile(path.join(distPath, 'index.html'))
})

app.listen(config.port, () => {
  console.log(`\n  Résumé agent backend → http://localhost:${config.port}`)
  console.log(`  • llm  : ${config.llm.apiKey ? `tailor=${config.llm.models.tailor}` : 'NOT configured'}`)
  console.log(`  • auth : ${config.firebase.authDisabled ? 'DISABLED (dev)' : 'Firebase ID tokens'}`)
  console.log(`  • quota: ${isQuotaEnabled() ? 'enforced (Admin Firestore)' : 'NOT enforced (no creds)'}\n`)
})